spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8088"

jwt:
  secret: ${SECRET_KEY:iIV7aCZjFda+ubeOWRHTU4NeXNCvEwo0qMojLwz84yw=}
  access-token-expiration: 3600000
  refresh-token-expiration: 432000000